services:
  movie_reservation:
    container_name: movie_reservation
    image: node:latest
    working_dir: /usr/src/app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: npm run start:dev
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: movie_reservation_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movie_reservation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
